### PR TITLE
my try to add small search models in webui

### PR DESCRIPTION
**Pull request by MrTimoxaYT**
I tried to implement a table with a search for models that are loaded from a json file as it was done in stable diffusion by AUTOMATIC 1111. The list of models can be updated simply by adding them to the index file, I hope my meager skills were enough to do something good
functions send a lot of requests to the index file, unfortunately my skills were not enough to optimize the search process, but the main thing is the idea... am I right?)
image

before load models list
image

after
image

after click on tag
image

search test
image

### CODE REVIEW

**Comment by SociallyIneptWeeb** [comment]
Do you think we should just add the json file to the git directly? This way we don't have to make multiple requests.

**Comment by MrTimoxaYT** [comment]
sounds good

**Comment by SociallyIneptWeeb** [comment]
Whoops sorry about the conflict haha

**Comment by MrTimoxaYT** [comment]
Sheeeesh, I'm in your yt video)))

**Comment by SociallyIneptWeeb** [comment]
LOL you saw it so fast

**Comment by SociallyIneptWeeb** [comment]
But yah its thanks to your pull request that I made the video haha

**Comment by MrTimoxaYT** [comment]
🤔🤔🤔🤔😑😑😑😑😑😘😘😘😘😘😘

**Comment by MrTimoxaYT** [comment]
sheeesh, I just now noticed that it is impossible to do an easy merge(((((
should I recreate the pull request?

**Comment by MrTimoxaYT** [comment]
sheesh..... Ok, now i add credit and i find all people in index model file, im get some tests and create new pull....

**Pull request closed without merging**
