### PR TITLE
web UI for AICoverGen

### PR DESCRIPTION
**Pull request by MrTimoxaYT**
just a web ui for AICoverGen, created with gradio
main tab
image

download model tab
image

### CODE REVIEW

**Comment by SociallyIneptWeeb** [comment]
This looks good, may I know which version of Gradio you're using? It seems to be taking extremely long to install gradio without version restrictions.

**Comment by MrTimoxaYT** [comment]
I don't know, I just install it with pip and write code)
I think, I use last version

**Comment by SociallyIneptWeeb** [comment]
Ok I tried it using gradio==3.35.0 but seem to be getting an error, with no error message. Can you try using this version and testing it?

**Comment by MrTimoxaYT** [comment]
as I understand it, in version 3.35.0 in gradio, the library code was slightly different than in 3.39.0 on which I wrote, this is noticeable when you launch the web.py different versions of gradio show different UI

this difference in versions stops the code from working, although the web ui starts
the buttons don't work on version 3.35.0, although everything works on version 3.39.0 

ver 3.35.0
image

ver 3.39.0 (on which I wrote the code for web.py)
image

**Comment by SociallyIneptWeeb** [comment]
Ok, it looks good. I'll merge it for now, and once I have updated some parts of the gradio code tmr, I'll add its usage to the readme so others can use it as well. Thank you!

**Pull request merged**
