### PR TITLE
Replicate API Added

### PR DESCRIPTION
**Pull request by zsxkib**
Hey @SociallyIneptWeeb,

I watched your Youtube videos to create this, great work!!

I've added these three models onto Replicate:
- https://replicate.com/zsxkib/create-rvc-dataset
   - to go from youtube to dataset 
- https://replicate.com/replicate/train-rvc-model
    - to train a model on replicate
- https://replicate.com/zsxkib/realistic-voice-cloning
    -  it's on the front page of Replicate w/ ~10K hits!
    - Check out the examples we've added: https://replicate.com/zsxkib/realistic-voice-cloning/examples

There's also a Colab Notebook to tie this all together using Replicate API calls: https://colab.research.google.com/drive/1G-OEJlcIfq-3v6GMlt12D09tuArqsJOF?usp=sharing

We'll also be releasing a blog post about how to fine-tune your own custom dataset, train, and use the model in the next few days.

All of this thanks to your work! ❤️‍🔥

### CODE REVIEW

**Comment by SociallyIneptWeeb** [comment]
Thanks a lot! May I know how merging this pull request will change how users perform their generations? I'm not too familiar with Replicate, does this allow users to use Replicate's GPU instead of their own? Also do users mainly use Replicate's website for generations or do they use the AICoverGen's Gradio frontend?

**Comment by zsxkib** [comment]
Omg I totally forgot to reply

**Comment by zsxkib** [comment]
Hey @SociallyIneptWeeb,

My bad for the super late reply. Let me catch you up on what this integration does:

So basically, I added some files (.dockerignore, cog.yaml, and predict.py) to make your project run smoothly on Replicate. Don't worry, it doesn't mess with your core code at all. It's just a wrapper to get your model working on our platform.

Here's what this means for your users:

1. API access: They can hit your model through our API. Like this:

```bash
curl -X POST \
  -H "Authorization: Bearer $REPLICATE_API_TOKEN" \
  -H "Content-Type: application/json" \
  -d '{
    "version": "0a9c7c558af4c0f20667c1bd1260ce32a2879944a0b9e44e1398660c077b1550",
    "input": {
      "protect": 0.33,
      "rvc_model": "Squidward",
      "index_rate": 0.5,
      "song_input": "https://replicate.delivery/pbxt/JsPIizFfRy54Jk5LuXdnrNdV1JHJ6oLmPPdRuIfh3lvpoNai/gangnam.mp3",
      // other params...
    }
  }' \
  https://api.replicate.com/v1/predictions
```

2. Web UI: There's a web interface at https://replicate.com/zsxkib/realistic-voice-cloning

3. GPU access: Your model runs on our GPU nodes, so people without beefy hardware can still use it.

4. Cog stuff: Devs can run predictions locally using Cog if they want.

The cool thing is, users have options now. They can still use your Gradio frontend, or they can use our web UI or API. Plus, they can run it on our GPUs instead of their own machine if they want.

Oh, and we dropped a blog post about using your model for voice cloning: https://replicate.com/blog/how-to-tune-a-realistic-voice-clone. It covers making a dataset, training a custom voice model, and generating audio.

Your model's blowing up, by the way. Tons of examples at https://replicate.com/zsxkib/realistic-voice-cloning/examples.

Let me know if you want me to explain any of this stuff more. Always happy to break it down further if you need.

**Comment by SociallyIneptWeeb** [comment]
I see! Thanks for the explanation, I'll gladly merge these changes!

**Pull request merged**
